//---------------------------------------------------------------------------

#ifndef MeldTygH
#define MeldTygH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <QuickRpt.hpp>
#include <QRCtrls.hpp>
#include <ComCtrls.hpp>
//---------------------------------------------------------------------------
class TMeldTygQRP : public TForm
{
__published:	// IDE-managed Components
	TPageControl *PageControl1;
	TTabSheet *Tytul;
	TTabSheet *TabSheet2;
	TTabSheet *TabSheet3;
	TQuickRep *m_SprzPrzyjQR;
	TQRBand *m_PageHeaderQB;
	TQRExpr *QRExpr2;
	TQRBand *m_DetailPrzyjQB;
	TQRExpr *m_NrMagQE;
	TQRShape *QRShape11;
	TQRExpr *QRLabel2;
	TQRShape *QRShape12;
	TQRExpr *QRLabel3;
	TQRShape *QRShape13;
	TQRExpr *m_NazSprzPrzyjQRE;
	TQRShape *QRShape14;
	TQRExpr *QRLabel5;
	TQRShape *QRShape15;
	TQRExpr *m_JWPrzyjQRE;
	TQRShape *QRShape16;
	TQRExpr *m_ProtStTechPrzyjQRE;
	TQRShape *QRShape17;
	TQRExpr *QRLabel8;
	TQRShape *QRShape18;
	TQRExpr *m_ProtPrzyjQRE;
	TQRShape *QRShape19;
	TQRExpr *QRLabel10;
	TQRShape *QRShape20;
	TQRExpr *QRLabel11;
	TQRBand *PageFooterBand1;
	TQRChildBand *m_TitleChildQB;
	TQRChildBand *ChildBand1;
	TQRLabel *QRLabel1;
	TQRShape *QRShape21;
	TQRLabel *QRLabel12;
	TQRShape *QRShape22;
	TQRLabel *QRLabel13;
	TQRShape *QRShape23;
	TQRLabel *QRLabel14;
	TQRShape *QRShape24;
	TQRLabel *QRLabel15;
	TQRShape *QRShape25;
	TQRLabel *QRLabel16;
	TQRShape *QRShape26;
	TQRLabel *QRLabel17;
	TQRShape *QRShape27;
	TQRLabel *QRLabel18;
	TQRShape *QRShape28;
	TQRLabel *QRLabel19;
	TQRShape *QRShape29;
	TQRLabel *QRLabel20;
	TQRShape *QRShape30;
	TQRLabel *QRLabel21;
	TQuickRep *m_TitleQR;
	TQRBand *QRBand2;
	TQRExpr *QRExpr4;
	TQRChildBand *QRChildBand5;
	TQRBand *m_Title1BA;
	TQRLabel *QRLabel22;
	TQRBand *ColumnHeaderBand1;
	TQRLabel *QRLabel23;
	TQRShape *QRShape1;
	TQRLabel *QRLabel24;
	TQRShape *QRShape2;
	TQRLabel *QRLabel25;
	TQRShape *QRShape3;
	TQRLabel *QRLabel26;
	TQRShape *QRShape4;
	TQRLabel *QRLabel27;
	TQRShape *QRShape5;
	TQRLabel *QRLabel28;
	TQRShape *QRShape6;
	TQRLabel *QRLabel29;
	TQRShape *QRShape7;
	TQRLabel *QRLabel30;
	TQRShape *QRShape8;
	TQRLabel *QRLabel31;
	TQRShape *QRShape9;
	TQRLabel *QRLabel32;
	TQRShape *QRShape10;
	TQRLabel *QRLabel33;
	TQRBand *SummaryBand1;
	TQRSysData *QRSysData1;
	TQRSysData *QRSysData2;
        TQuickRep *m_SprzPrzekQR;
	TQRBand *QRBand1;
	TQRExpr *QRExpr1;
	TQRBand *QRBand3;
	TQRExpr *QRExpr3;
	TQRShape *QRShape31;
	TQRExpr *m_NazSprzPrzekQRE;
	TQRShape *QRShape34;
	TQRExpr *QRExpr8;
	TQRShape *QRShape35;
	TQRExpr *m_JWPrzekQRE;
	TQRShape *QRShape36;
	TQRExpr *m_ProtPrzekQRE;
	TQRShape *QRShape39;
	TQRExpr *QRExpr13;
	TQRShape *QRShape40;
	TQRExpr *QRExpr14;
	TQRBand *QRBand4;
	TQRSysData *QRSysData3;
	TQRSysData *QRSysData4;
	TQRChildBand *QRChildBand1;
	TQRChildBand *QRChildBand2;
	TQRLabel *QRLabel34;
	TQRShape *QRShape41;
	TQRLabel *QRLabel37;
	TQRShape *QRShape44;
	TQRLabel *QRLabel38;
	TQRShape *QRShape45;
	TQRLabel *QRLabel39;
	TQRShape *QRShape46;
	TQRLabel *QRLabel42;
	TQRShape *QRShape49;
	TQRLabel *QRLabel43;
	TQRShape *QRShape50;
	TQRLabel *QRLabel44;
	TQRBand *QRBand5;
	TQRLabel *QRLabel45;
	TQRBand *QRBand6;
	TQRLabel *QRLabel46;
	TQRShape *QRShape51;
	TQRLabel *QRLabel49;
	TQRShape *QRShape54;
	TQRLabel *QRLabel50;
	TQRShape *QRShape55;
	TQRLabel *QRLabel51;
	TQRShape *QRShape56;
	TQRLabel *QRLabel54;
	TQRShape *QRShape59;
	TQRLabel *QRLabel55;
	TQRShape *QRShape60;
	TQRLabel *QRLabel56;
	TQRBand *QRBand7;
	TTabSheet *TabSheet1;
        TQuickRep *m_SprzRemQR;
	TQRBand *QRBand8;
	TQRExpr *QRExpr5;
	TQRBand *QRBand9;
	TQRExpr *m_NazSprzRemQRE;
	TQRShape *QRShape38;
	TQRExpr *QRExpr16;
	TQRShape *QRShape42;
	TQRExpr *m_JWRemQRE;
	TQRShape *QRShape43;
	TQRExpr *m_KutRemQRE;
	TQRShape *QRShape47;
	TQRExpr *QRExpr19;
	TQRShape *QRShape53;
	TQRExpr *QRExpr22;
	TQRBand *QRBand10;
	TQRSysData *QRSysData5;
	TQRSysData *QRSysData6;
	TQRChildBand *QRChildBand3;
	TQRChildBand *QRChildBand4;
	TQRLabel *QRLabel41;
	TQRShape *QRShape62;
	TQRLabel *QRLabel47;
	TQRShape *QRShape63;
	TQRLabel *QRLabel48;
	TQRShape *QRShape64;
	TQRLabel *QRLabel52;
	TQRShape *QRShape65;
	TQRLabel *QRLabel53;
	TQRShape *QRShape67;
	TQRLabel *QRLabel58;
	TQRShape *QRShape68;
	TQRLabel *QRLabel59;
	TQRBand *QRBand11;
	TQRLabel *QRLabel60;
	TQRBand *QRBand12;
	TQRLabel *QRLabel64;
	TQRShape *QRShape72;
	TQRLabel *QRLabel65;
	TQRShape *QRShape73;
	TQRLabel *QRLabel66;
	TQRShape *QRShape74;
	TQRLabel *QRLabel67;
	TQRShape *QRShape75;
	TQRLabel *QRLabel68;
	TQRShape *QRShape77;
	TQRLabel *QRLabel70;
	TQRShape *QRShape78;
	TQRLabel *QRLabel71;
	TQRBand *QRBand13;
        TQRShape *QRShape52;
        TQRExpr *QRExpr6;
        TTabSheet *TabSheet4;
        TQuickRep *m_SprzDepQR;
        TQRBand *QRBand14;
        TQRExpr *QRExpr10;
        TQRBand *QRBand15;
        TQRExpr *QRExpr11;
        TQRShape *QRShape32;
        TQRExpr *QRExpr20;
        TQRShape *QRShape33;
	TQRExpr *m_NazSprzDepQRE;
        TQRShape *QRShape48;
        TQRExpr *QRExpr24;
        TQRShape *QRShape57;
	TQRExpr *m_JWDepQRE;
        TQRShape *QRShape58;
	TQRExpr *m_ProtStTechDepQRE;
        TQRShape *QRShape61;
        TQRExpr *QRExpr27;
        TQRShape *QRShape66;
	TQRExpr *m_ProtDepQRE;
        TQRShape *QRShape69;
        TQRExpr *QRExpr29;
        TQRShape *QRShape70;
        TQRExpr *QRExpr30;
        TQRBand *QRBand16;
        TQRSysData *QRSysData7;
        TQRSysData *QRSysData8;
        TQRChildBand *QRChildBand6;
        TQRChildBand *QRChildBand7;
        TQRLabel *QRLabel35;
        TQRShape *QRShape71;
        TQRLabel *QRLabel36;
        TQRShape *QRShape76;
        TQRLabel *QRLabel57;
        TQRShape *QRShape80;
        TQRLabel *QRLabel61;
        TQRShape *QRShape81;
        TQRLabel *QRLabel62;
        TQRShape *QRShape82;
        TQRLabel *QRLabel63;
        TQRShape *QRShape83;
        TQRLabel *QRLabel69;
        TQRShape *QRShape84;
        TQRLabel *QRLabel72;
        TQRShape *QRShape85;
        TQRLabel *QRLabel73;
        TQRShape *QRShape86;
        TQRLabel *QRLabel74;
        TQRBand *QRBand17;
        TQRLabel *QRLabel75;
        TQRBand *QRBand18;
        TQRLabel *QRLabel76;
        TQRShape *QRShape87;
        TQRLabel *QRLabel77;
        TQRShape *QRShape88;
        TQRLabel *QRLabel79;
        TQRShape *QRShape90;
        TQRLabel *QRLabel80;
        TQRShape *QRShape91;
        TQRLabel *QRLabel81;
        TQRShape *QRShape92;
        TQRLabel *QRLabel82;
        TQRShape *QRShape93;
        TQRLabel *QRLabel83;
        TQRShape *QRShape94;
        TQRLabel *QRLabel84;
        TQRShape *QRShape95;
        TQRLabel *QRLabel85;
        TQRShape *QRShape96;
        TQRLabel *QRLabel86;
        TQRBand *QRBand19;
        TTabSheet *TabSheet5;
        TQuickRep *m_PodsumQR;
        TQRBand *QRBand20;
        TQRChildBand *QRChildBand8;
        TQRMemo *m_UwagiWnioskiQRM;
        TQRMemo *QRMemo1;
        TQRCompositeReport *m_CompQR;
	void __fastcall m_CompQRAddReports(TObject *Sender);
	void __fastcall m_DetailPrzyjQBBeforePrint(TQRCustomBand *Sender, bool &PrintBand);
	void __fastcall QRBand3BeforePrint(TQRCustomBand *Sender, bool &PrintBand);
	void __fastcall QRBand9BeforePrint(TQRCustomBand *Sender, bool &PrintBand);
	void __fastcall QRBand15BeforePrint(TQRCustomBand *Sender, bool &PrintBand);
public:
		//INTERFEJS
		  void  __fastcall setSprzPrzyjDS(TDataSet* _DS);
		  void  __fastcall setSprzPrzekDS(TDataSet* _DS);
		  void  __fastcall setSprzRemDS(TDataSet* _DS);
		  void  __fastcall setSprzDepDS(TDataSet* _DS);
		  void 	__fastcall print(void);
		  void 	__fastcall preview(void);
		//KONSTRUKTOR DESTRUKTOR
				__fastcall  TMeldTygQRP(TComponent* Owner);
				__fastcall ~TMeldTygQRP(void);
private:
		//METODY POMOCNICZE
		  void __fastcall prepare(void);
		  int  __fastcall countBandLines(int & Lines, TQRExpr* _Ex, const AnsiString& _Val);
		//STA£E
		  static const int M_BAND_HEIGHT;
		  static const int M_EXPR_HEIGHT;
		  static const int M_SHAPE_HEIGHT;
};
//---------------------------------------------------------------------------
#endif
